### get index
GET http://localhost:3000/

### ask
POST http://localhost:3000/ask
content-type: application/json

{
  "prompt": "Gimme a joke"
}





### local GET /
GET http://localhost:8888/.netlify/functions/api/

### local POST /ask
POST http://localhost:8888/.netlify/functions/api/ask
content-type: application/json

{
  "prompt": "Gimme a joke"
}



### get /api from deploy
GET https://pixiportfoliobackend.netlify.app/api


### get from deploy
GET https://pixiportfoliobackend.netlify.app/.netlify/functions/api

### get pixi from deploy
GET https://pixiportfoliobackend.netlify.app/.netlify/functions/pixi

### post from deploy
POST https://pixiportfoliobackend.netlify.app/.netlify/functions/api/ask
content-type: application/json

{
  "prompt": "Dame datos de un campeon de league of legends"
}
